version: "3.8"
services:
  spring_boot_rest_blog_database:
    container_name: blog_database
    image: mariadb
    environment:
      MARIADB_DATABASE: spring_boot_rest_blog_dev
      MARIADB_ROOT_PASSWORD: root
      MARIADB_ROOT_HOST: '%'
    ports:
      - "33062:3306"
  spring_boot_rest_blog_redis:
    container_name: blog_redis
    image: redis:latest
    ports:
      - "63790:6379"
    command: redis-server --loglevel warning --requirepass C8v8pY3@55Pe
    volumes:
        - cache:/data
volumes:
  cache:
    driver: local
