version: "3.8"
services:
  spring_boot_rest_blog_database:
    container_name: blog_database
    image: mariadb
    environment:
      MARIADB_DATABASE: spring_boot_rest_blog_dev
      MARIADB_ROOT_PASSWORD: root
      MARIADB_ROOT_HOST: '%'
    ports:
      - "33062:3306"
  spring_boot_rest_blog_redis:
    container_name: blog_redis
    image: redis:latest
    ports:
      - "63790:6379"
    command: redis-server --loglevel warning --requirepass C8v8pY3@55Pe
    volumes:
        - cache:/data
  spring_boot_rest_blog_zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: blog_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  spring_boot_rest_blog_broker:
    image: confluentinc/cp-kafka:latest
    container_name: blog_broker
    ports:
      # To learn about configuring Kafka for access across networks see
      # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
    depends_on:
      - spring_boot_rest_blog_zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'blog_zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://blog_broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
volumes:
  cache:
    driver: local
