spring:
  jpa:
    generate-ddl: true
    show-sql: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:33062/spring_boot_rest_blog_dev
    username: dev
    password: dev
  redis:
    host: localhost
    port: 63790

springdoc:
  swagger-ui:
    path: index.html
  paths-to-match:
    - /articles/**
