spring:
  jpa:
    generate-ddl: true
    show-sql: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:33062/spring_boot_rest_blog_dev
    username: dev
    password: dev
  redis:
    host: localhost
    port: 63790
    password: C8v8pY3@55Pe
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: spring_boot_rest_blog
    bootstrap-servers: localhost:9092

springdoc:
  swagger-ui:
    path: index.html
  paths-to-match:
    - /articles/**
